<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sirius" nsURI="http://www.polarsys.org/kitalpha/ad/sirius/1.0.0"
    nsPrefix="sirius">
  <eClassifiers xsi:type="ecore:EClass" name="SiriusRepresentation" eSuperTypes="platform:/plugin/org.polarsys.kitalpha.ad.viewpoint.coredomain/model/viewpoint.ecore#//RepresentationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="odesign" eType="ecore:EClass platform:/plugin/org.eclipse.sirius.model/model/viewpoint.ecore#//description/Group"/>
  </eClassifiers>
</ecore:EPackage>
