<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base"
    nsURI="http://org.polarsys.kitalpha/allocation/base/1.0.0" nsPrefix="org.polarsys.kitalpha.composer.metamodel.allocation.base">
  <eClassifiers xsi:type="ecore:EClass" name="Root" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFiles" upperBound="-1"
        eType="#//File" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTypes" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedElement" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
