/*******************************************************************************
 * Copyright (c) 2014 Thales Global Services S.A.S.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *  Thales Global Services S.A.S - initial API and implementation
 ******************************************************************************/
package constraint.provider.startup;

import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Plugin;
import org.eclipse.core.runtime.Status;
import org.eclipse.emf.examples.extlibrary.EXTLibraryPackage;
import org.osgi.framework.BundleContext;

/**
 * The activator class controls the plug-in life cycle This class has been
 * automaticaly generated by eclipse plugin wizard then i added "getID" and
 * "log" methods as in OCLValidationExamplePlugin they are used by our
 * OCLConstraintProvider class to log parse errors
 */
public class Activator extends Plugin {

	// The shared instance
	private static Activator plugin;

	/**
	 * Returns the shared instance
	 * 
	 * @return the shared instance
	 */
	public static Activator getDefault() {
		return plugin;
	}

	public static String getID() {
		return getDefault().getBundle().getSymbolicName();
	}

	public static void log(String message, Throwable t) {
		getDefault().getLog().log(
				new Status(IStatus.ERROR, getID(), 1, message, t));
	}

	/**
	 * The constructor
	 */
	public Activator() {
		super();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.eclipse.ui.plugin.AbstractUIPlugin#start(org.osgi.framework.BundleContext)
	 */
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		plugin = this;
		EXTLibraryPackage.eINSTANCE.eClass();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.eclipse.ui.plugin.AbstractUIPlugin#stop(org.osgi.framework.BundleContext)
	 */
	@Override
	public void stop(BundleContext context) throws Exception {
		plugin = null;
		super.stop(context);
	}

}
