<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="services"
    nsURI="http://www.polarsys.org/kitalpha/ad/viewpoint/dsl/cs/text/vpservices/1.0.0"
    nsPrefix="services">
  <eClassifiers xsi:type="ecore:EClass" name="Services">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.polarsys.kitalpha.ad.viewpoint.dsl.as.desc/model/vpdesc.ecore#//Aspect"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
