<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="afdesc" nsURI="http://www.polarsys.org/kitalpha/ad/af/dsl/as/afdesc/1.0.0"
    nsPrefix="afdesc">
  <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/extension">
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
    <details key="useUUIDs" value="true"/>
    <details key="useIDAttributes" value="false"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFramework" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="af_aspects" upperBound="-1"
        eType="#//Aspect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="af_viewpoints" eType="#//Viewpoints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned_configuration" lowerBound="1"
        eType="#//Configuration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aspect" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned_element" upperBound="-1"
        eType="#//ConfigurationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationConfiguration" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootProjectName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Viewpoints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned_viewpoints" upperBound="-1"
        eType="ecore:EClass ../../org.polarsys.kitalpha.ad.viewpoint.dsl.as.desc/model/vpdesc.ecore#//Viewpoint"/>
  </eClassifiers>
</ecore:EPackage>
