<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ComponentSample" nsURI="http://www.polarsys.org/kitalpha/ComponentSample/1.0.0"
    nsPrefix="ComponentSample">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentElement" abstract="true" eSuperTypes="platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentModel" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" abstract="true" eSuperTypes="#//ComponentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackage" eSuperTypes="#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent" abstract="true" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="use" upperBound="-1" eType="#//AbstractComponent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareComponent" eSuperTypes="#//AbstractComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareComponent" eSuperTypes="#//AbstractComponent">
    <eAnnotations source="http://org.polarsys.kitalpha/documentation">
      <details key="description" value="Hardware Component"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractComponent" upperBound="-1"
        eType="#//AbstractComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentType">
    <eLiterals name="Behaviour" literal="Behaviour"/>
    <eLiterals name="Data" value="1" literal="Data"/>
    <eLiterals name="Service" value="2" literal="Service"/>
  </eClassifiers>
</ecore:EPackage>
