/*
 * generated by Xtext
 */
package org.polarsys.kitalpha.ad.viewpoint.dsl.cs.text.services;

import java.util.List;

import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

import com.google.inject.Inject;
import com.google.inject.Singleton;

@Singleton
public class ActivityexplorerGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ViewpointActivityExplorerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ViewpointActivityExplorer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cViewpointActivityExplorerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityExplorerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameFQNParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPagesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOwnedPagesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cOwnedPagesPageParserRuleCall_4_2_0 = (RuleCall)cOwnedPagesAssignment_4_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Assignment cOwnedPagesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOwnedPagesPageExtensionParserRuleCall_5_0 = (RuleCall)cOwnedPagesAssignment_5.eContents().get(0);
		private final Assignment cOwnedSectionExtensionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOwnedSectionExtensionsSectionExtensionParserRuleCall_6_0 = (RuleCall)cOwnedSectionExtensionsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		/// **
		// * @author: Faycal ABKA
		// * / ViewpointActivityExplorer returns activityExplorer::ViewpointActivityExplorer:
		//	{activityExplorer::ViewpointActivityExplorer} "activity-explorer" name=FQN "{" ("pages" "{" ownedPages+=Page* "}")?
		//	ownedPages+=PageExtension* ownedSectionExtensions+=SectionExtension* "}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::ViewpointActivityExplorer} "activity-explorer" name=FQN "{" ("pages" "{" ownedPages+=Page* "}")?
		//ownedPages+=PageExtension* ownedSectionExtensions+=SectionExtension* "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::ViewpointActivityExplorer}
		public Action getViewpointActivityExplorerAction_0() { return cViewpointActivityExplorerAction_0; }

		//"activity-explorer"
		public Keyword getActivityExplorerKeyword_1() { return cActivityExplorerKeyword_1; }

		//name=FQN
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//FQN
		public RuleCall getNameFQNParserRuleCall_2_0() { return cNameFQNParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("pages" "{" ownedPages+=Page* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"pages"
		public Keyword getPagesKeyword_4_0() { return cPagesKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//ownedPages+=Page*
		public Assignment getOwnedPagesAssignment_4_2() { return cOwnedPagesAssignment_4_2; }

		//Page
		public RuleCall getOwnedPagesPageParserRuleCall_4_2_0() { return cOwnedPagesPageParserRuleCall_4_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_3() { return cRightCurlyBracketKeyword_4_3; }

		//ownedPages+=PageExtension*
		public Assignment getOwnedPagesAssignment_5() { return cOwnedPagesAssignment_5; }

		//PageExtension
		public RuleCall getOwnedPagesPageExtensionParserRuleCall_5_0() { return cOwnedPagesPageExtensionParserRuleCall_5_0; }

		//ownedSectionExtensions+=SectionExtension*
		public Assignment getOwnedSectionExtensionsAssignment_6() { return cOwnedSectionExtensionsAssignment_6; }

		//SectionExtension
		public RuleCall getOwnedSectionExtensionsSectionExtensionParserRuleCall_6_0() { return cOwnedSectionExtensionsSectionExtensionParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class AbstractPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractPage");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPageExtensionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractPage returns activityExplorer::AbstractPage:
		//	Page | PageExtension;
		@Override public ParserRule getRule() { return rule; }

		//Page | PageExtension
		public Alternatives getAlternatives() { return cAlternatives; }

		//Page
		public RuleCall getPageParserRuleCall_0() { return cPageParserRuleCall_0; }

		//PageExtension
		public RuleCall getPageExtensionParserRuleCall_1() { return cPageExtensionParserRuleCall_1; }
	}

	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFileExtensionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFileExtensionsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFileExtensionsSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cFileExtensionsAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cActivityExplorerItemIDAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cActivityExplorerItemIDFQNParserRuleCall_6_1_0 = (RuleCall)cActivityExplorerItemIDAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLabelKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLabelAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cLabelAssignment_7_1.eContents().get(0);
		private final Keyword cIndexKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cIndexAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cIndexEIntParserRuleCall_9_0 = (RuleCall)cIndexAssignment_9.eContents().get(0);
		private final Assignment cOwnedOverviewAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cOwnedOverviewOverviewParserRuleCall_10_0 = (RuleCall)cOwnedOverviewAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cHeaderKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Group cGroup_11_2 = (Group)cGroup_11.eContents().get(2);
		private final Keyword cImageOnKeyword_11_2_0 = (Keyword)cGroup_11_2.eContents().get(0);
		private final Keyword cColonKeyword_11_2_1 = (Keyword)cGroup_11_2.eContents().get(1);
		private final Assignment cImagePathOnAssignment_11_2_2 = (Assignment)cGroup_11_2.eContents().get(2);
		private final RuleCall cImagePathOnSTRINGTerminalRuleCall_11_2_2_0 = (RuleCall)cImagePathOnAssignment_11_2_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cImageOffKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Keyword cColonKeyword_11_3_1 = (Keyword)cGroup_11_3.eContents().get(1);
		private final Assignment cImagePathOffAssignment_11_3_2 = (Assignment)cGroup_11_3.eContents().get(2);
		private final RuleCall cImagePathOffSTRINGTerminalRuleCall_11_3_2_0 = (RuleCall)cImagePathOffAssignment_11_3_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cTabNameKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cTabNameAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cTabNameSTRINGTerminalRuleCall_12_1_0 = (RuleCall)cTabNameAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cPredicatedKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cColonKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cHasPredicateAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cHasPredicateEBooleanParserRuleCall_13_2_0 = (RuleCall)cHasPredicateAssignment_13_2.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cShowViewerKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cColonKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cShowViewerAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final RuleCall cShowViewerEBooleanParserRuleCall_14_2_0 = (RuleCall)cShowViewerAssignment_14_2.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cSectionsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cOwnedSectionsAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final RuleCall cOwnedSectionsSectionParserRuleCall_15_2_0 = (RuleCall)cOwnedSectionsAssignment_15_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15_3 = (Keyword)cGroup_15.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Page returns activityExplorer::Page:
		//	{activityExplorer::Page} "page" name=ID "{" ("description" description=STRING)? ("file-extension"
		//	fileExtensions=STRING)? ("id" activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt
		//	ownedOverview=Overview? ("header" "{" ("image-on" ":" imagePathOn=STRING)? ("image-off" ":" imagePathOff=STRING)?
		//	"}")? ("tab-name" tabName=STRING)? ("predicated" ":" hasPredicate=EBoolean)? ("show-viewer" ":" showViewer=EBoolean)?
		//	("sections" "{" ownedSections+=Section* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::Page} "page" name=ID "{" ("description" description=STRING)? ("file-extension"
		//fileExtensions=STRING)? ("id" activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt
		//ownedOverview=Overview? ("header" "{" ("image-on" ":" imagePathOn=STRING)? ("image-off" ":" imagePathOff=STRING)?
		//"}")? ("tab-name" tabName=STRING)? ("predicated" ":" hasPredicate=EBoolean)? ("show-viewer" ":" showViewer=EBoolean)?
		//("sections" "{" ownedSections+=Section* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Page}
		public Action getPageAction_0() { return cPageAction_0; }

		//"page"
		public Keyword getPageKeyword_1() { return cPageKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }

		//("file-extension" fileExtensions=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"file-extension"
		public Keyword getFileExtensionKeyword_5_0() { return cFileExtensionKeyword_5_0; }

		//fileExtensions=STRING
		public Assignment getFileExtensionsAssignment_5_1() { return cFileExtensionsAssignment_5_1; }

		//STRING
		public RuleCall getFileExtensionsSTRINGTerminalRuleCall_5_1_0() { return cFileExtensionsSTRINGTerminalRuleCall_5_1_0; }

		//("id" activityExplorerItemID=FQN)?
		public Group getGroup_6() { return cGroup_6; }

		//"id"
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }

		//activityExplorerItemID=FQN
		public Assignment getActivityExplorerItemIDAssignment_6_1() { return cActivityExplorerItemIDAssignment_6_1; }

		//FQN
		public RuleCall getActivityExplorerItemIDFQNParserRuleCall_6_1_0() { return cActivityExplorerItemIDFQNParserRuleCall_6_1_0; }

		//("label" label=STRING)?
		public Group getGroup_7() { return cGroup_7; }

		//"label"
		public Keyword getLabelKeyword_7_0() { return cLabelKeyword_7_0; }

		//label=STRING
		public Assignment getLabelAssignment_7_1() { return cLabelAssignment_7_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_7_1_0() { return cLabelSTRINGTerminalRuleCall_7_1_0; }

		//"index"
		public Keyword getIndexKeyword_8() { return cIndexKeyword_8; }

		//index=EInt
		public Assignment getIndexAssignment_9() { return cIndexAssignment_9; }

		//EInt
		public RuleCall getIndexEIntParserRuleCall_9_0() { return cIndexEIntParserRuleCall_9_0; }

		//ownedOverview=Overview?
		public Assignment getOwnedOverviewAssignment_10() { return cOwnedOverviewAssignment_10; }

		//Overview
		public RuleCall getOwnedOverviewOverviewParserRuleCall_10_0() { return cOwnedOverviewOverviewParserRuleCall_10_0; }

		//("header" "{" ("image-on" ":" imagePathOn=STRING)? ("image-off" ":" imagePathOff=STRING)? "}")?
		public Group getGroup_11() { return cGroup_11; }

		//"header"
		public Keyword getHeaderKeyword_11_0() { return cHeaderKeyword_11_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }

		//("image-on" ":" imagePathOn=STRING)?
		public Group getGroup_11_2() { return cGroup_11_2; }

		//"image-on"
		public Keyword getImageOnKeyword_11_2_0() { return cImageOnKeyword_11_2_0; }

		//":"
		public Keyword getColonKeyword_11_2_1() { return cColonKeyword_11_2_1; }

		//imagePathOn=STRING
		public Assignment getImagePathOnAssignment_11_2_2() { return cImagePathOnAssignment_11_2_2; }

		//STRING
		public RuleCall getImagePathOnSTRINGTerminalRuleCall_11_2_2_0() { return cImagePathOnSTRINGTerminalRuleCall_11_2_2_0; }

		//("image-off" ":" imagePathOff=STRING)?
		public Group getGroup_11_3() { return cGroup_11_3; }

		//"image-off"
		public Keyword getImageOffKeyword_11_3_0() { return cImageOffKeyword_11_3_0; }

		//":"
		public Keyword getColonKeyword_11_3_1() { return cColonKeyword_11_3_1; }

		//imagePathOff=STRING
		public Assignment getImagePathOffAssignment_11_3_2() { return cImagePathOffAssignment_11_3_2; }

		//STRING
		public RuleCall getImagePathOffSTRINGTerminalRuleCall_11_3_2_0() { return cImagePathOffSTRINGTerminalRuleCall_11_3_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }

		//("tab-name" tabName=STRING)?
		public Group getGroup_12() { return cGroup_12; }

		//"tab-name"
		public Keyword getTabNameKeyword_12_0() { return cTabNameKeyword_12_0; }

		//tabName=STRING
		public Assignment getTabNameAssignment_12_1() { return cTabNameAssignment_12_1; }

		//STRING
		public RuleCall getTabNameSTRINGTerminalRuleCall_12_1_0() { return cTabNameSTRINGTerminalRuleCall_12_1_0; }

		//("predicated" ":" hasPredicate=EBoolean)?
		public Group getGroup_13() { return cGroup_13; }

		//"predicated"
		public Keyword getPredicatedKeyword_13_0() { return cPredicatedKeyword_13_0; }

		//":"
		public Keyword getColonKeyword_13_1() { return cColonKeyword_13_1; }

		//hasPredicate=EBoolean
		public Assignment getHasPredicateAssignment_13_2() { return cHasPredicateAssignment_13_2; }

		//EBoolean
		public RuleCall getHasPredicateEBooleanParserRuleCall_13_2_0() { return cHasPredicateEBooleanParserRuleCall_13_2_0; }

		//("show-viewer" ":" showViewer=EBoolean)?
		public Group getGroup_14() { return cGroup_14; }

		//"show-viewer"
		public Keyword getShowViewerKeyword_14_0() { return cShowViewerKeyword_14_0; }

		//":"
		public Keyword getColonKeyword_14_1() { return cColonKeyword_14_1; }

		//showViewer=EBoolean
		public Assignment getShowViewerAssignment_14_2() { return cShowViewerAssignment_14_2; }

		//EBoolean
		public RuleCall getShowViewerEBooleanParserRuleCall_14_2_0() { return cShowViewerEBooleanParserRuleCall_14_2_0; }

		//("sections" "{" ownedSections+=Section* "}")?
		public Group getGroup_15() { return cGroup_15; }

		//"sections"
		public Keyword getSectionsKeyword_15_0() { return cSectionsKeyword_15_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_15_1() { return cLeftCurlyBracketKeyword_15_1; }

		//ownedSections+=Section*
		public Assignment getOwnedSectionsAssignment_15_2() { return cOwnedSectionsAssignment_15_2; }

		//Section
		public RuleCall getOwnedSectionsSectionParserRuleCall_15_2_0() { return cOwnedSectionsSectionParserRuleCall_15_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15_3() { return cRightCurlyBracketKeyword_15_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}

	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Section");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cActivityExplorerItemIDAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cActivityExplorerItemIDFQNParserRuleCall_5_1_0 = (RuleCall)cActivityExplorerItemIDAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLabelKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cLabelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cLabelAssignment_6_1.eContents().get(0);
		private final Keyword cIndexKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIndexAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cIndexEIntParserRuleCall_8_0 = (RuleCall)cIndexAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cFilteringKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cFilteringAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cFilteringEBooleanParserRuleCall_9_2_0 = (RuleCall)cFilteringAssignment_9_2.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cExpandedKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cColonKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cExpandedAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cExpandedEBooleanParserRuleCall_10_2_0 = (RuleCall)cExpandedAssignment_10_2.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cActivitiesKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cOwnedActivitiesAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cOwnedActivitiesActivityParserRuleCall_11_2_0 = (RuleCall)cOwnedActivitiesAssignment_11_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Section returns activityExplorer::Section:
		//	{activityExplorer::Section} "section" name=ID "{" ("description" description=STRING)? ("id"
		//	activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt ("filtering" ":" filtering=EBoolean)?
		//	("expanded" ":" expanded=EBoolean)? ("activities" "{" ownedActivities+=Activity* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::Section} "section" name=ID "{" ("description" description=STRING)? ("id" activityExplorerItemID=FQN)?
		//("label" label=STRING)? "index" index=EInt ("filtering" ":" filtering=EBoolean)? ("expanded" ":" expanded=EBoolean)?
		//("activities" "{" ownedActivities+=Activity* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Section}
		public Action getSectionAction_0() { return cSectionAction_0; }

		//"section"
		public Keyword getSectionKeyword_1() { return cSectionKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }

		//("id" activityExplorerItemID=FQN)?
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//activityExplorerItemID=FQN
		public Assignment getActivityExplorerItemIDAssignment_5_1() { return cActivityExplorerItemIDAssignment_5_1; }

		//FQN
		public RuleCall getActivityExplorerItemIDFQNParserRuleCall_5_1_0() { return cActivityExplorerItemIDFQNParserRuleCall_5_1_0; }

		//("label" label=STRING)?
		public Group getGroup_6() { return cGroup_6; }

		//"label"
		public Keyword getLabelKeyword_6_0() { return cLabelKeyword_6_0; }

		//label=STRING
		public Assignment getLabelAssignment_6_1() { return cLabelAssignment_6_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_6_1_0() { return cLabelSTRINGTerminalRuleCall_6_1_0; }

		//"index"
		public Keyword getIndexKeyword_7() { return cIndexKeyword_7; }

		//index=EInt
		public Assignment getIndexAssignment_8() { return cIndexAssignment_8; }

		//EInt
		public RuleCall getIndexEIntParserRuleCall_8_0() { return cIndexEIntParserRuleCall_8_0; }

		//("filtering" ":" filtering=EBoolean)?
		public Group getGroup_9() { return cGroup_9; }

		//"filtering"
		public Keyword getFilteringKeyword_9_0() { return cFilteringKeyword_9_0; }

		//":"
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }

		//filtering=EBoolean
		public Assignment getFilteringAssignment_9_2() { return cFilteringAssignment_9_2; }

		//EBoolean
		public RuleCall getFilteringEBooleanParserRuleCall_9_2_0() { return cFilteringEBooleanParserRuleCall_9_2_0; }

		//("expanded" ":" expanded=EBoolean)?
		public Group getGroup_10() { return cGroup_10; }

		//"expanded"
		public Keyword getExpandedKeyword_10_0() { return cExpandedKeyword_10_0; }

		//":"
		public Keyword getColonKeyword_10_1() { return cColonKeyword_10_1; }

		//expanded=EBoolean
		public Assignment getExpandedAssignment_10_2() { return cExpandedAssignment_10_2; }

		//EBoolean
		public RuleCall getExpandedEBooleanParserRuleCall_10_2_0() { return cExpandedEBooleanParserRuleCall_10_2_0; }

		//("activities" "{" ownedActivities+=Activity* "}")?
		public Group getGroup_11() { return cGroup_11; }

		//"activities"
		public Keyword getActivitiesKeyword_11_0() { return cActivitiesKeyword_11_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }

		//ownedActivities+=Activity*
		public Assignment getOwnedActivitiesAssignment_11_2() { return cOwnedActivitiesAssignment_11_2; }

		//Activity
		public RuleCall getOwnedActivitiesActivityParserRuleCall_11_2_0() { return cOwnedActivitiesActivityParserRuleCall_11_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11_3() { return cRightCurlyBracketKeyword_11_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActivityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cActivityExplorerItemIDAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cActivityExplorerItemIDFQNParserRuleCall_5_1_0 = (RuleCall)cActivityExplorerItemIDAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLabelKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cLabelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cLabelAssignment_6_1.eContents().get(0);
		private final Keyword cIndexKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIndexAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cIndexEIntParserRuleCall_8_0 = (RuleCall)cIndexAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPredicatedKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cHasPredicateAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cHasPredicateEBooleanParserRuleCall_9_2_0 = (RuleCall)cHasPredicateAssignment_9_2.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cIconKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cColonKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cImagePathOffAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cImagePathOffSTRINGTerminalRuleCall_10_2_0 = (RuleCall)cImagePathOffAssignment_10_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Activity returns activityExplorer::Activity:
		//	{activityExplorer::Activity} "activity" name=ID "{" ("description" description=STRING)? ("id"
		//	activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt ("predicated" ":" hasPredicate=EBoolean)?
		//	("icon" ":" imagePathOff=STRING)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::Activity} "activity" name=ID "{" ("description" description=STRING)? ("id"
		//activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt ("predicated" ":" hasPredicate=EBoolean)?
		//("icon" ":" imagePathOff=STRING)? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Activity}
		public Action getActivityAction_0() { return cActivityAction_0; }

		//"activity"
		public Keyword getActivityKeyword_1() { return cActivityKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }

		//("id" activityExplorerItemID=FQN)?
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//activityExplorerItemID=FQN
		public Assignment getActivityExplorerItemIDAssignment_5_1() { return cActivityExplorerItemIDAssignment_5_1; }

		//FQN
		public RuleCall getActivityExplorerItemIDFQNParserRuleCall_5_1_0() { return cActivityExplorerItemIDFQNParserRuleCall_5_1_0; }

		//("label" label=STRING)?
		public Group getGroup_6() { return cGroup_6; }

		//"label"
		public Keyword getLabelKeyword_6_0() { return cLabelKeyword_6_0; }

		//label=STRING
		public Assignment getLabelAssignment_6_1() { return cLabelAssignment_6_1; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_6_1_0() { return cLabelSTRINGTerminalRuleCall_6_1_0; }

		//"index"
		public Keyword getIndexKeyword_7() { return cIndexKeyword_7; }

		//index=EInt
		public Assignment getIndexAssignment_8() { return cIndexAssignment_8; }

		//EInt
		public RuleCall getIndexEIntParserRuleCall_8_0() { return cIndexEIntParserRuleCall_8_0; }

		//("predicated" ":" hasPredicate=EBoolean)?
		public Group getGroup_9() { return cGroup_9; }

		//"predicated"
		public Keyword getPredicatedKeyword_9_0() { return cPredicatedKeyword_9_0; }

		//":"
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }

		//hasPredicate=EBoolean
		public Assignment getHasPredicateAssignment_9_2() { return cHasPredicateAssignment_9_2; }

		//EBoolean
		public RuleCall getHasPredicateEBooleanParserRuleCall_9_2_0() { return cHasPredicateEBooleanParserRuleCall_9_2_0; }

		//("icon" ":" imagePathOff=STRING)?
		public Group getGroup_10() { return cGroup_10; }

		//"icon"
		public Keyword getIconKeyword_10_0() { return cIconKeyword_10_0; }

		//":"
		public Keyword getColonKeyword_10_1() { return cColonKeyword_10_1; }

		//imagePathOff=STRING
		public Assignment getImagePathOffAssignment_10_2() { return cImagePathOffAssignment_10_2; }

		//STRING
		public RuleCall getImagePathOffSTRINGTerminalRuleCall_10_2_0() { return cImagePathOffSTRINGTerminalRuleCall_10_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class PageExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PageExtension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPageExtensionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPageExtensionsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cExtendedPageKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExtendedPageIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExtendedPageIDFQNParserRuleCall_4_0 = (RuleCall)cExtendedPageIDAssignment_4.eContents().get(0);
		private final Assignment cOwnedSectionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOwnedSectionsSectionParserRuleCall_5_0 = (RuleCall)cOwnedSectionsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//PageExtension returns activityExplorer::PageExtension:
		//	{activityExplorer::PageExtension} "page-extensions" "{" "extended-page" extendedPageID=FQN ownedSections+=Section*
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::PageExtension} "page-extensions" "{" "extended-page" extendedPageID=FQN ownedSections+=Section* "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::PageExtension}
		public Action getPageExtensionAction_0() { return cPageExtensionAction_0; }

		//"page-extensions"
		public Keyword getPageExtensionsKeyword_1() { return cPageExtensionsKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"extended-page"
		public Keyword getExtendedPageKeyword_3() { return cExtendedPageKeyword_3; }

		//extendedPageID=FQN
		public Assignment getExtendedPageIDAssignment_4() { return cExtendedPageIDAssignment_4; }

		//FQN
		public RuleCall getExtendedPageIDFQNParserRuleCall_4_0() { return cExtendedPageIDFQNParserRuleCall_4_0; }

		//ownedSections+=Section*
		public Assignment getOwnedSectionsAssignment_5() { return cOwnedSectionsAssignment_5; }

		//Section
		public RuleCall getOwnedSectionsSectionParserRuleCall_5_0() { return cOwnedSectionsSectionParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class SectionExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SectionExtension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSectionExtensionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSectionExtensionsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cExtendedSectionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExtendedSectionIDAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExtendedSectionIDFQNParserRuleCall_4_0 = (RuleCall)cExtendedSectionIDAssignment_4.eContents().get(0);
		private final Assignment cOwnedActivitiesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOwnedActivitiesActivityParserRuleCall_5_0 = (RuleCall)cOwnedActivitiesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SectionExtension returns activityExplorer::SectionExtension:
		//	{activityExplorer::SectionExtension} "section-extensions" "{" "extended-section" extendedSectionID=FQN
		//	ownedActivities+=Activity* "}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::SectionExtension} "section-extensions" "{" "extended-section" extendedSectionID=FQN
		//ownedActivities+=Activity* "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::SectionExtension}
		public Action getSectionExtensionAction_0() { return cSectionExtensionAction_0; }

		//"section-extensions"
		public Keyword getSectionExtensionsKeyword_1() { return cSectionExtensionsKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"extended-section"
		public Keyword getExtendedSectionKeyword_3() { return cExtendedSectionKeyword_3; }

		//extendedSectionID=FQN
		public Assignment getExtendedSectionIDAssignment_4() { return cExtendedSectionIDAssignment_4; }

		//FQN
		public RuleCall getExtendedSectionIDFQNParserRuleCall_4_0() { return cExtendedSectionIDFQNParserRuleCall_4_0; }

		//ownedActivities+=Activity*
		public Assignment getOwnedActivitiesAssignment_5() { return cOwnedActivitiesAssignment_5; }

		//Activity
		public RuleCall getOwnedActivitiesActivityParserRuleCall_5_0() { return cOwnedActivitiesActivityParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class OverviewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Overview");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOverviewAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOverviewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cImageOnKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cImagePathOnAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cImagePathOnSTRINGTerminalRuleCall_4_2_0 = (RuleCall)cImagePathOnAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cImageOffKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cColonKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cImagePathOffAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cImagePathOffSTRINGTerminalRuleCall_5_2_0 = (RuleCall)cImagePathOffAssignment_5_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Overview returns activityExplorer::Overview:
		//	{activityExplorer::Overview} "Overview" "{" ("description" description=STRING)? ("image-on" ":" imagePathOn=STRING)?
		//	("image-off" ":" imagePathOff=STRING)? "}";
		@Override public ParserRule getRule() { return rule; }

		//{activityExplorer::Overview} "Overview" "{" ("description" description=STRING)? ("image-on" ":" imagePathOn=STRING)?
		//("image-off" ":" imagePathOff=STRING)? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Overview}
		public Action getOverviewAction_0() { return cOverviewAction_0; }

		//"Overview"
		public Keyword getOverviewKeyword_1() { return cOverviewKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("description" description=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"description"
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_1_0() { return cDescriptionSTRINGTerminalRuleCall_3_1_0; }

		//("image-on" ":" imagePathOn=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"image-on"
		public Keyword getImageOnKeyword_4_0() { return cImageOnKeyword_4_0; }

		//":"
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }

		//imagePathOn=STRING
		public Assignment getImagePathOnAssignment_4_2() { return cImagePathOnAssignment_4_2; }

		//STRING
		public RuleCall getImagePathOnSTRINGTerminalRuleCall_4_2_0() { return cImagePathOnSTRINGTerminalRuleCall_4_2_0; }

		//("image-off" ":" imagePathOff=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"image-off"
		public Keyword getImageOffKeyword_5_0() { return cImageOffKeyword_5_0; }

		//":"
		public Keyword getColonKeyword_5_1() { return cColonKeyword_5_1; }

		//imagePathOff=STRING
		public Assignment getImagePathOffAssignment_5_2() { return cImagePathOffAssignment_5_2; }

		//STRING
		public RuleCall getImagePathOffSTRINGTerminalRuleCall_5_2_0() { return cImagePathOffSTRINGTerminalRuleCall_5_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final ViewpointActivityExplorerElements pViewpointActivityExplorer;
	private final AbstractPageElements pAbstractPage;
	private final PageElements pPage;
	private final SectionElements pSection;
	private final ActivityElements pActivity;
	private final PageExtensionElements pPageExtension;
	private final SectionExtensionElements pSectionExtension;
	private final OverviewElements pOverview;
	
	private final Grammar grammar;

	private final CommonGrammarAccess gaCommon;

	@Inject
	public ActivityexplorerGrammarAccess(GrammarProvider grammarProvider,
		CommonGrammarAccess gaCommon) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaCommon = gaCommon;
		this.pViewpointActivityExplorer = new ViewpointActivityExplorerElements();
		this.pAbstractPage = new AbstractPageElements();
		this.pPage = new PageElements();
		this.pSection = new SectionElements();
		this.pActivity = new ActivityElements();
		this.pPageExtension = new PageExtensionElements();
		this.pSectionExtension = new SectionExtensionElements();
		this.pOverview = new OverviewElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.polarsys.kitalpha.ad.viewpoint.dsl.cs.text.Activityexplorer".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public CommonGrammarAccess getCommonGrammarAccess() {
		return gaCommon;
	}

	
	/// **
	// * @author: Faycal ABKA
	// * / ViewpointActivityExplorer returns activityExplorer::ViewpointActivityExplorer:
	//	{activityExplorer::ViewpointActivityExplorer} "activity-explorer" name=FQN "{" ("pages" "{" ownedPages+=Page* "}")?
	//	ownedPages+=PageExtension* ownedSectionExtensions+=SectionExtension* "}";
	public ViewpointActivityExplorerElements getViewpointActivityExplorerAccess() {
		return pViewpointActivityExplorer;
	}
	
	public ParserRule getViewpointActivityExplorerRule() {
		return getViewpointActivityExplorerAccess().getRule();
	}

	//AbstractPage returns activityExplorer::AbstractPage:
	//	Page | PageExtension;
	public AbstractPageElements getAbstractPageAccess() {
		return pAbstractPage;
	}
	
	public ParserRule getAbstractPageRule() {
		return getAbstractPageAccess().getRule();
	}

	//Page returns activityExplorer::Page:
	//	{activityExplorer::Page} "page" name=ID "{" ("description" description=STRING)? ("file-extension"
	//	fileExtensions=STRING)? ("id" activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt
	//	ownedOverview=Overview? ("header" "{" ("image-on" ":" imagePathOn=STRING)? ("image-off" ":" imagePathOff=STRING)?
	//	"}")? ("tab-name" tabName=STRING)? ("predicated" ":" hasPredicate=EBoolean)? ("show-viewer" ":" showViewer=EBoolean)?
	//	("sections" "{" ownedSections+=Section* "}")? "}";
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//Section returns activityExplorer::Section:
	//	{activityExplorer::Section} "section" name=ID "{" ("description" description=STRING)? ("id"
	//	activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt ("filtering" ":" filtering=EBoolean)?
	//	("expanded" ":" expanded=EBoolean)? ("activities" "{" ownedActivities+=Activity* "}")? "}";
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}

	//Activity returns activityExplorer::Activity:
	//	{activityExplorer::Activity} "activity" name=ID "{" ("description" description=STRING)? ("id"
	//	activityExplorerItemID=FQN)? ("label" label=STRING)? "index" index=EInt ("predicated" ":" hasPredicate=EBoolean)?
	//	("icon" ":" imagePathOff=STRING)? "}";
	public ActivityElements getActivityAccess() {
		return pActivity;
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//PageExtension returns activityExplorer::PageExtension:
	//	{activityExplorer::PageExtension} "page-extensions" "{" "extended-page" extendedPageID=FQN ownedSections+=Section*
	//	"}";
	public PageExtensionElements getPageExtensionAccess() {
		return pPageExtension;
	}
	
	public ParserRule getPageExtensionRule() {
		return getPageExtensionAccess().getRule();
	}

	//SectionExtension returns activityExplorer::SectionExtension:
	//	{activityExplorer::SectionExtension} "section-extensions" "{" "extended-section" extendedSectionID=FQN
	//	ownedActivities+=Activity* "}";
	public SectionExtensionElements getSectionExtensionAccess() {
		return pSectionExtension;
	}
	
	public ParserRule getSectionExtensionRule() {
		return getSectionExtensionAccess().getRule();
	}

	//Overview returns activityExplorer::Overview:
	//	{activityExplorer::Overview} "Overview" "{" ("description" description=STRING)? ("image-on" ":" imagePathOn=STRING)?
	//	("image-off" ":" imagePathOff=STRING)? "}";
	public OverviewElements getOverviewAccess() {
		return pOverview;
	}
	
	public ParserRule getOverviewRule() {
		return getOverviewAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public CommonGrammarAccess.EStringElements getEStringAccess() {
		return gaCommon.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//FQN returns ecore::EString:
	//	ID ("." => ID)*;
	public CommonGrammarAccess.FQNElements getFQNAccess() {
		return gaCommon.getFQNAccess();
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public CommonGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaCommon.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	INT;
	public CommonGrammarAccess.EIntElements getEIntAccess() {
		return gaCommon.getEIntAccess();
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaCommon.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaCommon.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaCommon.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaCommon.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaCommon.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaCommon.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaCommon.getANY_OTHERRule();
	} 
}
