/*
* generated by Xtext
*/

package org.polarsys.kitalpha.ad.viewpoint.dsl.cs.text.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.polarsys.kitalpha.ad.viewpoint.dsl.cs.text.services.CommonGrammarAccess;

@Singleton
public class ActivityexplorerGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ViewpointActivityExplorerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ViewpointActivityExplorer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cViewpointActivityExplorerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExplorerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameFQNParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPagesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOwnedPagesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOwnedPagesPageParserRuleCall_5_2_0 = (RuleCall)cOwnedPagesAssignment_5_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Assignment cOwnedPagesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOwnedPagesPageExtensionParserRuleCall_6_0 = (RuleCall)cOwnedPagesAssignment_6.eContents().get(0);
		private final Assignment cOwnedSectionExtensionsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOwnedSectionExtensionsSectionExtensionParserRuleCall_7_0 = (RuleCall)cOwnedSectionExtensionsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		/// **
		//
		// * @author: Faycal ABKA
		//
		// * / ViewpointActivityExplorer returns activityExplorer::ViewpointActivityExplorer:
		//
		//	{activityExplorer::ViewpointActivityExplorer} "activity" "explorer" name=FQN "{" ("pages" "{" ownedPages+=Page* "}")?
		//
		//	ownedPages+=PageExtension* ownedSectionExtensions+=SectionExtension* "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::ViewpointActivityExplorer} "activity" "explorer" name=FQN "{" ("pages" "{" ownedPages+=Page* "}")?
		//
		//ownedPages+=PageExtension* ownedSectionExtensions+=SectionExtension* "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::ViewpointActivityExplorer}
		public Action getViewpointActivityExplorerAction_0() { return cViewpointActivityExplorerAction_0; }

		//"activity"
		public Keyword getActivityKeyword_1() { return cActivityKeyword_1; }

		//"explorer"
		public Keyword getExplorerKeyword_2() { return cExplorerKeyword_2; }

		//name=FQN
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//FQN
		public RuleCall getNameFQNParserRuleCall_3_0() { return cNameFQNParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("pages" "{" ownedPages+=Page* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"pages"
		public Keyword getPagesKeyword_5_0() { return cPagesKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//ownedPages+=Page*
		public Assignment getOwnedPagesAssignment_5_2() { return cOwnedPagesAssignment_5_2; }

		//Page
		public RuleCall getOwnedPagesPageParserRuleCall_5_2_0() { return cOwnedPagesPageParserRuleCall_5_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_3() { return cRightCurlyBracketKeyword_5_3; }

		//ownedPages+=PageExtension*
		public Assignment getOwnedPagesAssignment_6() { return cOwnedPagesAssignment_6; }

		//PageExtension
		public RuleCall getOwnedPagesPageExtensionParserRuleCall_6_0() { return cOwnedPagesPageExtensionParserRuleCall_6_0; }

		//ownedSectionExtensions+=SectionExtension*
		public Assignment getOwnedSectionExtensionsAssignment_7() { return cOwnedSectionExtensionsAssignment_7; }

		//SectionExtension
		public RuleCall getOwnedSectionExtensionsSectionExtensionParserRuleCall_7_0() { return cOwnedSectionExtensionsSectionExtensionParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class AbstractPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractPage");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPageExtensionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractPage returns activityExplorer::AbstractPage:
		//
		//	Page | PageExtension;
		public ParserRule getRule() { return rule; }

		//Page | PageExtension
		public Alternatives getAlternatives() { return cAlternatives; }

		//Page
		public RuleCall getPageParserRuleCall_0() { return cPageParserRuleCall_0; }

		//PageExtension
		public RuleCall getPageExtensionParserRuleCall_1() { return cPageExtensionParserRuleCall_1; }
	}

	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFileKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cExtensionKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cFileExtensionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cFileExtensionsSTRINGTerminalRuleCall_5_2_0 = (RuleCall)cFileExtensionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cIdKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cActivityExplorerItemIDAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cActivityExplorerItemIDFQNParserRuleCall_6_1_0 = (RuleCall)cActivityExplorerItemIDAssignment_6_1.eContents().get(0);
		private final Keyword cIndexKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cIndexAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cIndexEIntParserRuleCall_8_0 = (RuleCall)cIndexAssignment_8.eContents().get(0);
		private final Assignment cOwnedOverviewAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cOwnedOverviewOverviewParserRuleCall_9_0 = (RuleCall)cOwnedOverviewAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cHeaderKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cImageKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Keyword cOnKeyword_10_2_1 = (Keyword)cGroup_10_2.eContents().get(1);
		private final Keyword cColonKeyword_10_2_2 = (Keyword)cGroup_10_2.eContents().get(2);
		private final Assignment cImagePathOnAssignment_10_2_3 = (Assignment)cGroup_10_2.eContents().get(3);
		private final RuleCall cImagePathOnSTRINGTerminalRuleCall_10_2_3_0 = (RuleCall)cImagePathOnAssignment_10_2_3.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cImageKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Keyword cOffKeyword_10_3_1 = (Keyword)cGroup_10_3.eContents().get(1);
		private final Keyword cColonKeyword_10_3_2 = (Keyword)cGroup_10_3.eContents().get(2);
		private final Assignment cImagePathOffAssignment_10_3_3 = (Assignment)cGroup_10_3.eContents().get(3);
		private final RuleCall cImagePathOffSTRINGTerminalRuleCall_10_3_3_0 = (RuleCall)cImagePathOffAssignment_10_3_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cTabKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cNameKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cTabNameAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cTabNameSTRINGTerminalRuleCall_11_2_0 = (RuleCall)cTabNameAssignment_11_2.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cPredicatedKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cColonKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cHasPredicateAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cHasPredicateEBooleanParserRuleCall_12_2_0 = (RuleCall)cHasPredicateAssignment_12_2.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cShowKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cViewerKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Keyword cColonKeyword_13_2 = (Keyword)cGroup_13.eContents().get(2);
		private final Assignment cShowViewerAssignment_13_3 = (Assignment)cGroup_13.eContents().get(3);
		private final RuleCall cShowViewerEBooleanParserRuleCall_13_3_0 = (RuleCall)cShowViewerAssignment_13_3.eContents().get(0);
		private final Keyword cSectionsKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cLeftCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cOwnedSectionsAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cOwnedSectionsSectionParserRuleCall_16_0 = (RuleCall)cOwnedSectionsAssignment_16.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//Page returns activityExplorer::Page:
		//
		//	{activityExplorer::Page} "page" name=STRING "{" ("description" description=STRING)? ("file" "extension"
		//
		//	fileExtensions=STRING)? ("id" activityExplorerItemID=FQN)? "index" index=EInt ownedOverview=Overview? ("header" "{"
		//
		//	("image" "on" ":" imagePathOn=STRING)? ("image" "off" ":" imagePathOff=STRING)? "}")? ("tab" "name" tabName=STRING)?
		//
		//	("predicated" ":" hasPredicate=EBoolean)? ("show" "viewer" ":" showViewer=EBoolean)? "sections" "{"
		//
		//	ownedSections+=Section* "}" "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::Page} "page" name=STRING "{" ("description" description=STRING)? ("file" "extension"
		//
		//fileExtensions=STRING)? ("id" activityExplorerItemID=FQN)? "index" index=EInt ownedOverview=Overview? ("header" "{"
		//
		//("image" "on" ":" imagePathOn=STRING)? ("image" "off" ":" imagePathOff=STRING)? "}")? ("tab" "name" tabName=STRING)?
		//
		//("predicated" ":" hasPredicate=EBoolean)? ("show" "viewer" ":" showViewer=EBoolean)? "sections" "{"
		//
		//ownedSections+=Section* "}" "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Page}
		public Action getPageAction_0() { return cPageAction_0; }

		//"page"
		public Keyword getPageKeyword_1() { return cPageKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }

		//("file" "extension" fileExtensions=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"file"
		public Keyword getFileKeyword_5_0() { return cFileKeyword_5_0; }

		//"extension"
		public Keyword getExtensionKeyword_5_1() { return cExtensionKeyword_5_1; }

		//fileExtensions=STRING
		public Assignment getFileExtensionsAssignment_5_2() { return cFileExtensionsAssignment_5_2; }

		//STRING
		public RuleCall getFileExtensionsSTRINGTerminalRuleCall_5_2_0() { return cFileExtensionsSTRINGTerminalRuleCall_5_2_0; }

		//("id" activityExplorerItemID=FQN)?
		public Group getGroup_6() { return cGroup_6; }

		//"id"
		public Keyword getIdKeyword_6_0() { return cIdKeyword_6_0; }

		//activityExplorerItemID=FQN
		public Assignment getActivityExplorerItemIDAssignment_6_1() { return cActivityExplorerItemIDAssignment_6_1; }

		//FQN
		public RuleCall getActivityExplorerItemIDFQNParserRuleCall_6_1_0() { return cActivityExplorerItemIDFQNParserRuleCall_6_1_0; }

		//"index"
		public Keyword getIndexKeyword_7() { return cIndexKeyword_7; }

		//index=EInt
		public Assignment getIndexAssignment_8() { return cIndexAssignment_8; }

		//EInt
		public RuleCall getIndexEIntParserRuleCall_8_0() { return cIndexEIntParserRuleCall_8_0; }

		//ownedOverview=Overview?
		public Assignment getOwnedOverviewAssignment_9() { return cOwnedOverviewAssignment_9; }

		//Overview
		public RuleCall getOwnedOverviewOverviewParserRuleCall_9_0() { return cOwnedOverviewOverviewParserRuleCall_9_0; }

		//("header" "{" ("image" "on" ":" imagePathOn=STRING)? ("image" "off" ":" imagePathOff=STRING)? "}")?
		public Group getGroup_10() { return cGroup_10; }

		//"header"
		public Keyword getHeaderKeyword_10_0() { return cHeaderKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//("image" "on" ":" imagePathOn=STRING)?
		public Group getGroup_10_2() { return cGroup_10_2; }

		//"image"
		public Keyword getImageKeyword_10_2_0() { return cImageKeyword_10_2_0; }

		//"on"
		public Keyword getOnKeyword_10_2_1() { return cOnKeyword_10_2_1; }

		//":"
		public Keyword getColonKeyword_10_2_2() { return cColonKeyword_10_2_2; }

		//imagePathOn=STRING
		public Assignment getImagePathOnAssignment_10_2_3() { return cImagePathOnAssignment_10_2_3; }

		//STRING
		public RuleCall getImagePathOnSTRINGTerminalRuleCall_10_2_3_0() { return cImagePathOnSTRINGTerminalRuleCall_10_2_3_0; }

		//("image" "off" ":" imagePathOff=STRING)?
		public Group getGroup_10_3() { return cGroup_10_3; }

		//"image"
		public Keyword getImageKeyword_10_3_0() { return cImageKeyword_10_3_0; }

		//"off"
		public Keyword getOffKeyword_10_3_1() { return cOffKeyword_10_3_1; }

		//":"
		public Keyword getColonKeyword_10_3_2() { return cColonKeyword_10_3_2; }

		//imagePathOff=STRING
		public Assignment getImagePathOffAssignment_10_3_3() { return cImagePathOffAssignment_10_3_3; }

		//STRING
		public RuleCall getImagePathOffSTRINGTerminalRuleCall_10_3_3_0() { return cImagePathOffSTRINGTerminalRuleCall_10_3_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }

		//("tab" "name" tabName=STRING)?
		public Group getGroup_11() { return cGroup_11; }

		//"tab"
		public Keyword getTabKeyword_11_0() { return cTabKeyword_11_0; }

		//"name"
		public Keyword getNameKeyword_11_1() { return cNameKeyword_11_1; }

		//tabName=STRING
		public Assignment getTabNameAssignment_11_2() { return cTabNameAssignment_11_2; }

		//STRING
		public RuleCall getTabNameSTRINGTerminalRuleCall_11_2_0() { return cTabNameSTRINGTerminalRuleCall_11_2_0; }

		//("predicated" ":" hasPredicate=EBoolean)?
		public Group getGroup_12() { return cGroup_12; }

		//"predicated"
		public Keyword getPredicatedKeyword_12_0() { return cPredicatedKeyword_12_0; }

		//":"
		public Keyword getColonKeyword_12_1() { return cColonKeyword_12_1; }

		//hasPredicate=EBoolean
		public Assignment getHasPredicateAssignment_12_2() { return cHasPredicateAssignment_12_2; }

		//EBoolean
		public RuleCall getHasPredicateEBooleanParserRuleCall_12_2_0() { return cHasPredicateEBooleanParserRuleCall_12_2_0; }

		//("show" "viewer" ":" showViewer=EBoolean)?
		public Group getGroup_13() { return cGroup_13; }

		//"show"
		public Keyword getShowKeyword_13_0() { return cShowKeyword_13_0; }

		//"viewer"
		public Keyword getViewerKeyword_13_1() { return cViewerKeyword_13_1; }

		//":"
		public Keyword getColonKeyword_13_2() { return cColonKeyword_13_2; }

		//showViewer=EBoolean
		public Assignment getShowViewerAssignment_13_3() { return cShowViewerAssignment_13_3; }

		//EBoolean
		public RuleCall getShowViewerEBooleanParserRuleCall_13_3_0() { return cShowViewerEBooleanParserRuleCall_13_3_0; }

		//"sections"
		public Keyword getSectionsKeyword_14() { return cSectionsKeyword_14; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_15() { return cLeftCurlyBracketKeyword_15; }

		//ownedSections+=Section*
		public Assignment getOwnedSectionsAssignment_16() { return cOwnedSectionsAssignment_16; }

		//Section
		public RuleCall getOwnedSectionsSectionParserRuleCall_16_0() { return cOwnedSectionsSectionParserRuleCall_16_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}

	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Section");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cActivityExplorerItemIDAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cActivityExplorerItemIDFQNParserRuleCall_5_1_0 = (RuleCall)cActivityExplorerItemIDAssignment_5_1.eContents().get(0);
		private final Keyword cIndexKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cIndexAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIndexEIntParserRuleCall_7_0 = (RuleCall)cIndexAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cFilteringKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cFilteringAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cFilteringEBooleanParserRuleCall_8_2_0 = (RuleCall)cFilteringAssignment_8_2.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cExpandedKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cExpandedAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cExpandedEBooleanParserRuleCall_9_2_0 = (RuleCall)cExpandedAssignment_9_2.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cActivitiesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cOwnedActivitiesAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cOwnedActivitiesActivityParserRuleCall_10_2_0 = (RuleCall)cOwnedActivitiesAssignment_10_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Section returns activityExplorer::Section:
		//
		//	{activityExplorer::Section} "section" name=STRING "{" ("description" description=STRING)? ("id"
		//
		//	activityExplorerItemID=FQN)? "index" index=EInt ("filtering" ":" filtering=EBoolean)? ("expanded" ":"
		//
		//	expanded=EBoolean)? ("activities" "{" ownedActivities+=Activity* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::Section} "section" name=STRING "{" ("description" description=STRING)? ("id"
		//
		//activityExplorerItemID=FQN)? "index" index=EInt ("filtering" ":" filtering=EBoolean)? ("expanded" ":"
		//
		//expanded=EBoolean)? ("activities" "{" ownedActivities+=Activity* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Section}
		public Action getSectionAction_0() { return cSectionAction_0; }

		//"section"
		public Keyword getSectionKeyword_1() { return cSectionKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }

		//("id" activityExplorerItemID=FQN)?
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//activityExplorerItemID=FQN
		public Assignment getActivityExplorerItemIDAssignment_5_1() { return cActivityExplorerItemIDAssignment_5_1; }

		//FQN
		public RuleCall getActivityExplorerItemIDFQNParserRuleCall_5_1_0() { return cActivityExplorerItemIDFQNParserRuleCall_5_1_0; }

		//"index"
		public Keyword getIndexKeyword_6() { return cIndexKeyword_6; }

		//index=EInt
		public Assignment getIndexAssignment_7() { return cIndexAssignment_7; }

		//EInt
		public RuleCall getIndexEIntParserRuleCall_7_0() { return cIndexEIntParserRuleCall_7_0; }

		//("filtering" ":" filtering=EBoolean)?
		public Group getGroup_8() { return cGroup_8; }

		//"filtering"
		public Keyword getFilteringKeyword_8_0() { return cFilteringKeyword_8_0; }

		//":"
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }

		//filtering=EBoolean
		public Assignment getFilteringAssignment_8_2() { return cFilteringAssignment_8_2; }

		//EBoolean
		public RuleCall getFilteringEBooleanParserRuleCall_8_2_0() { return cFilteringEBooleanParserRuleCall_8_2_0; }

		//("expanded" ":" expanded=EBoolean)?
		public Group getGroup_9() { return cGroup_9; }

		//"expanded"
		public Keyword getExpandedKeyword_9_0() { return cExpandedKeyword_9_0; }

		//":"
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }

		//expanded=EBoolean
		public Assignment getExpandedAssignment_9_2() { return cExpandedAssignment_9_2; }

		//EBoolean
		public RuleCall getExpandedEBooleanParserRuleCall_9_2_0() { return cExpandedEBooleanParserRuleCall_9_2_0; }

		//("activities" "{" ownedActivities+=Activity* "}")?
		public Group getGroup_10() { return cGroup_10; }

		//"activities"
		public Keyword getActivitiesKeyword_10_0() { return cActivitiesKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//ownedActivities+=Activity*
		public Assignment getOwnedActivitiesAssignment_10_2() { return cOwnedActivitiesAssignment_10_2; }

		//Activity
		public RuleCall getOwnedActivitiesActivityParserRuleCall_10_2_0() { return cOwnedActivitiesActivityParserRuleCall_10_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_3() { return cRightCurlyBracketKeyword_10_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActivityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cActivityExplorerItemIDAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cActivityExplorerItemIDFQNParserRuleCall_5_1_0 = (RuleCall)cActivityExplorerItemIDAssignment_5_1.eContents().get(0);
		private final Keyword cIndexKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cIndexAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cIndexEIntParserRuleCall_7_0 = (RuleCall)cIndexAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPredicatedKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cHasPredicateAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cHasPredicateEBooleanParserRuleCall_8_2_0 = (RuleCall)cHasPredicateAssignment_8_2.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cIconKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cColonKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cImagePathOffAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cImagePathOffSTRINGTerminalRuleCall_9_2_0 = (RuleCall)cImagePathOffAssignment_9_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Activity returns activityExplorer::Activity:
		//
		//	{activityExplorer::Activity} "activity" name=STRING "{" ("description" description=STRING)? ("id"
		//
		//	activityExplorerItemID=FQN)? "index" index=EInt ("predicated" ":" hasPredicate=EBoolean)? ("icon" ":"
		//
		//	imagePathOff=STRING)? "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::Activity} "activity" name=STRING "{" ("description" description=STRING)? ("id"
		//
		//activityExplorerItemID=FQN)? "index" index=EInt ("predicated" ":" hasPredicate=EBoolean)? ("icon" ":"
		//
		//imagePathOff=STRING)? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Activity}
		public Action getActivityAction_0() { return cActivityAction_0; }

		//"activity"
		public Keyword getActivityKeyword_1() { return cActivityKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }

		//("id" activityExplorerItemID=FQN)?
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//activityExplorerItemID=FQN
		public Assignment getActivityExplorerItemIDAssignment_5_1() { return cActivityExplorerItemIDAssignment_5_1; }

		//FQN
		public RuleCall getActivityExplorerItemIDFQNParserRuleCall_5_1_0() { return cActivityExplorerItemIDFQNParserRuleCall_5_1_0; }

		//"index"
		public Keyword getIndexKeyword_6() { return cIndexKeyword_6; }

		//index=EInt
		public Assignment getIndexAssignment_7() { return cIndexAssignment_7; }

		//EInt
		public RuleCall getIndexEIntParserRuleCall_7_0() { return cIndexEIntParserRuleCall_7_0; }

		//("predicated" ":" hasPredicate=EBoolean)?
		public Group getGroup_8() { return cGroup_8; }

		//"predicated"
		public Keyword getPredicatedKeyword_8_0() { return cPredicatedKeyword_8_0; }

		//":"
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }

		//hasPredicate=EBoolean
		public Assignment getHasPredicateAssignment_8_2() { return cHasPredicateAssignment_8_2; }

		//EBoolean
		public RuleCall getHasPredicateEBooleanParserRuleCall_8_2_0() { return cHasPredicateEBooleanParserRuleCall_8_2_0; }

		//("icon" ":" imagePathOff=STRING)?
		public Group getGroup_9() { return cGroup_9; }

		//"icon"
		public Keyword getIconKeyword_9_0() { return cIconKeyword_9_0; }

		//":"
		public Keyword getColonKeyword_9_1() { return cColonKeyword_9_1; }

		//imagePathOff=STRING
		public Assignment getImagePathOffAssignment_9_2() { return cImagePathOffAssignment_9_2; }

		//STRING
		public RuleCall getImagePathOffSTRINGTerminalRuleCall_9_2_0() { return cImagePathOffSTRINGTerminalRuleCall_9_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class PageExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PageExtension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPageExtensionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExtensionsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cExtendedKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cPageKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExtendedPageIDAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExtendedPageIDFQNParserRuleCall_6_0 = (RuleCall)cExtendedPageIDAssignment_6.eContents().get(0);
		private final Assignment cOwnedSectionsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOwnedSectionsSectionParserRuleCall_7_0 = (RuleCall)cOwnedSectionsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//PageExtension returns activityExplorer::PageExtension:
		//
		//	{activityExplorer::PageExtension} "page" "extensions" "{" "extended" "page" extendedPageID=FQN
		//
		//	ownedSections+=Section* "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::PageExtension} "page" "extensions" "{" "extended" "page" extendedPageID=FQN ownedSections+=Section*
		//
		//"}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::PageExtension}
		public Action getPageExtensionAction_0() { return cPageExtensionAction_0; }

		//"page"
		public Keyword getPageKeyword_1() { return cPageKeyword_1; }

		//"extensions"
		public Keyword getExtensionsKeyword_2() { return cExtensionsKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"extended"
		public Keyword getExtendedKeyword_4() { return cExtendedKeyword_4; }

		//"page"
		public Keyword getPageKeyword_5() { return cPageKeyword_5; }

		//extendedPageID=FQN
		public Assignment getExtendedPageIDAssignment_6() { return cExtendedPageIDAssignment_6; }

		//FQN
		public RuleCall getExtendedPageIDFQNParserRuleCall_6_0() { return cExtendedPageIDFQNParserRuleCall_6_0; }

		//ownedSections+=Section*
		public Assignment getOwnedSectionsAssignment_7() { return cOwnedSectionsAssignment_7; }

		//Section
		public RuleCall getOwnedSectionsSectionParserRuleCall_7_0() { return cOwnedSectionsSectionParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class SectionExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SectionExtension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSectionExtensionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExtensionsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cExtendedKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cSectionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExtendedSectionIDAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExtendedSectionIDFQNParserRuleCall_6_0 = (RuleCall)cExtendedSectionIDAssignment_6.eContents().get(0);
		private final Assignment cOwnedActivitiesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOwnedActivitiesActivityParserRuleCall_7_0 = (RuleCall)cOwnedActivitiesAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//SectionExtension returns activityExplorer::SectionExtension:
		//
		//	{activityExplorer::SectionExtension} "section" "extensions" "{" "extended" "section" extendedSectionID=FQN
		//
		//	ownedActivities+=Activity* "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::SectionExtension} "section" "extensions" "{" "extended" "section" extendedSectionID=FQN
		//
		//ownedActivities+=Activity* "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::SectionExtension}
		public Action getSectionExtensionAction_0() { return cSectionExtensionAction_0; }

		//"section"
		public Keyword getSectionKeyword_1() { return cSectionKeyword_1; }

		//"extensions"
		public Keyword getExtensionsKeyword_2() { return cExtensionsKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//"extended"
		public Keyword getExtendedKeyword_4() { return cExtendedKeyword_4; }

		//"section"
		public Keyword getSectionKeyword_5() { return cSectionKeyword_5; }

		//extendedSectionID=FQN
		public Assignment getExtendedSectionIDAssignment_6() { return cExtendedSectionIDAssignment_6; }

		//FQN
		public RuleCall getExtendedSectionIDFQNParserRuleCall_6_0() { return cExtendedSectionIDFQNParserRuleCall_6_0; }

		//ownedActivities+=Activity*
		public Assignment getOwnedActivitiesAssignment_7() { return cOwnedActivitiesAssignment_7; }

		//Activity
		public RuleCall getOwnedActivitiesActivityParserRuleCall_7_0() { return cOwnedActivitiesActivityParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class OverviewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Overview");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOverviewAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOverviewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cImageKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cOnKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Keyword cColonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cImagePathOnAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cImagePathOnSTRINGTerminalRuleCall_4_3_0 = (RuleCall)cImagePathOnAssignment_4_3.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cImageKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cOffKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cColonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cImagePathOffAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cImagePathOffSTRINGTerminalRuleCall_5_3_0 = (RuleCall)cImagePathOffAssignment_5_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Overview returns activityExplorer::Overview:
		//
		//	{activityExplorer::Overview} "Overview" "{" ("description" description=STRING)? ("image" "on" ":"
		//
		//	imagePathOn=STRING)? ("image" "off" ":" imagePathOff=STRING)? "}";
		public ParserRule getRule() { return rule; }

		//{activityExplorer::Overview} "Overview" "{" ("description" description=STRING)? ("image" "on" ":" imagePathOn=STRING)?
		//
		//("image" "off" ":" imagePathOff=STRING)? "}"
		public Group getGroup() { return cGroup; }

		//{activityExplorer::Overview}
		public Action getOverviewAction_0() { return cOverviewAction_0; }

		//"Overview"
		public Keyword getOverviewKeyword_1() { return cOverviewKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("description" description=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"description"
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_1_0() { return cDescriptionSTRINGTerminalRuleCall_3_1_0; }

		//("image" "on" ":" imagePathOn=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"image"
		public Keyword getImageKeyword_4_0() { return cImageKeyword_4_0; }

		//"on"
		public Keyword getOnKeyword_4_1() { return cOnKeyword_4_1; }

		//":"
		public Keyword getColonKeyword_4_2() { return cColonKeyword_4_2; }

		//imagePathOn=STRING
		public Assignment getImagePathOnAssignment_4_3() { return cImagePathOnAssignment_4_3; }

		//STRING
		public RuleCall getImagePathOnSTRINGTerminalRuleCall_4_3_0() { return cImagePathOnSTRINGTerminalRuleCall_4_3_0; }

		//("image" "off" ":" imagePathOff=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"image"
		public Keyword getImageKeyword_5_0() { return cImageKeyword_5_0; }

		//"off"
		public Keyword getOffKeyword_5_1() { return cOffKeyword_5_1; }

		//":"
		public Keyword getColonKeyword_5_2() { return cColonKeyword_5_2; }

		//imagePathOff=STRING
		public Assignment getImagePathOffAssignment_5_3() { return cImagePathOffAssignment_5_3; }

		//STRING
		public RuleCall getImagePathOffSTRINGTerminalRuleCall_5_3_0() { return cImagePathOffSTRINGTerminalRuleCall_5_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private ViewpointActivityExplorerElements pViewpointActivityExplorer;
	private AbstractPageElements pAbstractPage;
	private PageElements pPage;
	private SectionElements pSection;
	private ActivityElements pActivity;
	private PageExtensionElements pPageExtension;
	private SectionExtensionElements pSectionExtension;
	private OverviewElements pOverview;
	
	private final Grammar grammar;

	private CommonGrammarAccess gaCommon;

	@Inject
	public ActivityexplorerGrammarAccess(GrammarProvider grammarProvider,
		CommonGrammarAccess gaCommon) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaCommon = gaCommon;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.polarsys.kitalpha.ad.viewpoint.dsl.cs.text.Activityexplorer".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public CommonGrammarAccess getCommonGrammarAccess() {
		return gaCommon;
	}

	
	/// **
	//
	// * @author: Faycal ABKA
	//
	// * / ViewpointActivityExplorer returns activityExplorer::ViewpointActivityExplorer:
	//
	//	{activityExplorer::ViewpointActivityExplorer} "activity" "explorer" name=FQN "{" ("pages" "{" ownedPages+=Page* "}")?
	//
	//	ownedPages+=PageExtension* ownedSectionExtensions+=SectionExtension* "}";
	public ViewpointActivityExplorerElements getViewpointActivityExplorerAccess() {
		return (pViewpointActivityExplorer != null) ? pViewpointActivityExplorer : (pViewpointActivityExplorer = new ViewpointActivityExplorerElements());
	}
	
	public ParserRule getViewpointActivityExplorerRule() {
		return getViewpointActivityExplorerAccess().getRule();
	}

	//AbstractPage returns activityExplorer::AbstractPage:
	//
	//	Page | PageExtension;
	public AbstractPageElements getAbstractPageAccess() {
		return (pAbstractPage != null) ? pAbstractPage : (pAbstractPage = new AbstractPageElements());
	}
	
	public ParserRule getAbstractPageRule() {
		return getAbstractPageAccess().getRule();
	}

	//Page returns activityExplorer::Page:
	//
	//	{activityExplorer::Page} "page" name=STRING "{" ("description" description=STRING)? ("file" "extension"
	//
	//	fileExtensions=STRING)? ("id" activityExplorerItemID=FQN)? "index" index=EInt ownedOverview=Overview? ("header" "{"
	//
	//	("image" "on" ":" imagePathOn=STRING)? ("image" "off" ":" imagePathOff=STRING)? "}")? ("tab" "name" tabName=STRING)?
	//
	//	("predicated" ":" hasPredicate=EBoolean)? ("show" "viewer" ":" showViewer=EBoolean)? "sections" "{"
	//
	//	ownedSections+=Section* "}" "}";
	public PageElements getPageAccess() {
		return (pPage != null) ? pPage : (pPage = new PageElements());
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//Section returns activityExplorer::Section:
	//
	//	{activityExplorer::Section} "section" name=STRING "{" ("description" description=STRING)? ("id"
	//
	//	activityExplorerItemID=FQN)? "index" index=EInt ("filtering" ":" filtering=EBoolean)? ("expanded" ":"
	//
	//	expanded=EBoolean)? ("activities" "{" ownedActivities+=Activity* "}")? "}";
	public SectionElements getSectionAccess() {
		return (pSection != null) ? pSection : (pSection = new SectionElements());
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}

	//Activity returns activityExplorer::Activity:
	//
	//	{activityExplorer::Activity} "activity" name=STRING "{" ("description" description=STRING)? ("id"
	//
	//	activityExplorerItemID=FQN)? "index" index=EInt ("predicated" ":" hasPredicate=EBoolean)? ("icon" ":"
	//
	//	imagePathOff=STRING)? "}";
	public ActivityElements getActivityAccess() {
		return (pActivity != null) ? pActivity : (pActivity = new ActivityElements());
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//PageExtension returns activityExplorer::PageExtension:
	//
	//	{activityExplorer::PageExtension} "page" "extensions" "{" "extended" "page" extendedPageID=FQN
	//
	//	ownedSections+=Section* "}";
	public PageExtensionElements getPageExtensionAccess() {
		return (pPageExtension != null) ? pPageExtension : (pPageExtension = new PageExtensionElements());
	}
	
	public ParserRule getPageExtensionRule() {
		return getPageExtensionAccess().getRule();
	}

	//SectionExtension returns activityExplorer::SectionExtension:
	//
	//	{activityExplorer::SectionExtension} "section" "extensions" "{" "extended" "section" extendedSectionID=FQN
	//
	//	ownedActivities+=Activity* "}";
	public SectionExtensionElements getSectionExtensionAccess() {
		return (pSectionExtension != null) ? pSectionExtension : (pSectionExtension = new SectionExtensionElements());
	}
	
	public ParserRule getSectionExtensionRule() {
		return getSectionExtensionAccess().getRule();
	}

	//Overview returns activityExplorer::Overview:
	//
	//	{activityExplorer::Overview} "Overview" "{" ("description" description=STRING)? ("image" "on" ":"
	//
	//	imagePathOn=STRING)? ("image" "off" ":" imagePathOff=STRING)? "}";
	public OverviewElements getOverviewAccess() {
		return (pOverview != null) ? pOverview : (pOverview = new OverviewElements());
	}
	
	public ParserRule getOverviewRule() {
		return getOverviewAccess().getRule();
	}

	//EString returns ecore::EString:
	//
	//	STRING | ID;
	public CommonGrammarAccess.EStringElements getEStringAccess() {
		return gaCommon.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//FQN returns ecore::EString:
	//
	//	ID ("." => ID)*;
	public CommonGrammarAccess.FQNElements getFQNAccess() {
		return gaCommon.getFQNAccess();
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//
	//	"true" | "false";
	public CommonGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaCommon.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//
	//	INT;
	public CommonGrammarAccess.EIntElements getEIntAccess() {
		return gaCommon.getEIntAccess();
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaCommon.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaCommon.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaCommon.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaCommon.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaCommon.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaCommon.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaCommon.getANY_OTHERRule();
	} 
}
