<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metadata" nsURI="http://www.polarsys.org/kitalpha/ad/metadata/1.0.0"
    nsPrefix="metadata">
  <eClassifiers xsi:type="ecore:EClass" name="Metadata" eSuperTypes="#//MetadataElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpointReferences" upperBound="-1"
        eType="#//ViewpointReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalMetadata" upperBound="-1"
        eType="#//Metadata"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewpointReference" eSuperTypes="#//MetadataElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vpId" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inactive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Version" instanceClassName="org.osgi.framework.Version"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetadataElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
